### PR TITLE
Improve interpolation tutorial

### PR DESCRIPTION
**Pull request by BjoernLudwigPTB**
The previous interpolation tutorial does not propagate any uncertainties and does not show the many capabilities of the implemented feature. This we want to change.

Check out, if everything works as expected on [Binder](https://mybinder.org/v2/gh/PTB-PSt1/PyDynamic_tutorials.git/introduce_interpolation_tutorial).

### CODE REVIEW

**Review by mgrub — COMMENTED** [review]
Thanks for the nice work. I really like the split of the tutorial into three parts of very managable size and the incorporation of interactive graphics. 

While reviewing the cells of the tutorials, I noticed some things, that we might want to adjust before merging:

- to incorporate your recent fix, we should require [pydynamic>=1.4.4](https://github.com/PTB-PSt1/PyDynamic/releases/tag/v1.4.4)
- regarding the ZeMA dataset:
  - Should we consider to add the possibility to download behind a proxy? (I'not sure, whether the `download`-package can handle this on its own.)
  - I think, the sampling frequency of the dataset should be 2kHz - only the original data was at 1MHz.
  - I really like the idea of using actual data from a real process. But currently, it looks like we need to download a 1GB file to process four datapoints - this does not seem very adequate. Maybe there is a similar smaller dataset we could use?

**Comment by BjoernLudwigPTB** [comment]
> Thanks for the nice work. I really like the split of the tutorial into three parts of very managable size and the incorporation of interactive graphics.
> 
> While reviewing the cells of the tutorials, I noticed some things, that we might want to adjust before merging:
> 
> * to incorporate your recent fix, we should require [pydynamic>=1.4.4](https://github.com/PTB-PSt1/PyDynamic/releases/tag/v1.4.4)
> * regarding the ZeMA dataset:
>   
>   * Should we consider to add the possibility to download behind a proxy? (I'not sure, whether the `download`-package can handle this on its own.)
>   * I think, the sampling frequency of the dataset should be 2kHz - only the original data was at 1MHz.
>   * I really like the idea of using actual data from a real process. But currently, it looks like we need to download a 1GB file to process four datapoints - this does not seem very adequate. Maybe there is a similar smaller dataset we could use?

Oh yes, these are all very valid. I will

- recompile the dependencies
- fix the sampling rate in the plots
- rearrange for downloading the data to a separate folder in the repository, to encourage using it in other tutorials as well

Last but not least: I could not reproduce the proxy problem on my PTB windows machine. Download works fine behind proxy without any more configuration. @mgrub Could you please try executing these in an environment, in which `download` is installed:

```python
>>> download("https://www.ptb.de/cms/fileadmin/templates/assets/logos/logo_ptb.png", "~/Downloads/logo_ptb.png", replace=True)
Downloading data from https://www.ptb.de/cms/fileadmin/templates/assets/logos/logo_ptb.png (9 kB)

file_sizes: 100%|██████████████████████████| 9.05k/9.05k [00:00<00:00, 1.32MB/s]
Successfully downloaded file to [...]/Downloads/logo_ptb.png
'[...]/Downloads/logo_ptb.png'
```

and

````python
>>> import urllib.request
>>> urllib.request.urlretrieve("https://www.ptb.de/cms/fileadmin/templates/assets/logos/logo_ptb.png", "~/Downloads/logo_ptb.png")
('[...]/Downloads/logo_ptb.png', <http.client.HTTPMessage object at 0x0000015545015B20>)
```

... and let me know, if these work?

**Comment by BjoernLudwigPTB** [comment]
Its all fixed now besides the proxy issue, since I could not reproduce it on my windows machine. Although I have to regret, that I did not try it with a Jupyter Notebook, but from the console (Power Shell and Python prompt).

**Review by mgrub — APPROVED** [review]
Cool, let's pull this request into the tutorials 😎

**Pull request merged**
